AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pdfkit-serverless

  Sample SAM Template for pdfkit-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30 # seconds

Resources:
  PdfkitFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pdfkit_serverless/
      Handler: app.lambda_handler
      Runtime: python3.7
      Layers:
        - !Ref DependenciesLayer
      Events:
        Pdfkit:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pdfkit
            Method: get

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
#      ContentUri: dependencies/ # for local development and testing
      ContentUri: dependencies.zip # for deployment

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PdfkitApi:
    Description: "API Gateway endpoint URL for Prod stage for Pdfkit function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pdfkit/"
  PdfkitFunction:
    Description: "Pdfkit Lambda Function ARN"
    Value: !GetAtt PdfkitFunction.Arn
  PdfkitFunctionIamRole:
    Description: "Implicit IAM Role created for Pdfkit function"
    Value: !GetAtt PdfkitFunctionRole.Arn
